# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
        run: |
          npm ci

      - name: Merge
        if: ${{ success() }}
        run: |
          git switch production
          git merge --no-ff --no-edit master

      - name: Build
        if: ${{ success() }}
        run: |
          git checkout -b temp/production
          npm run build
          git add -f build
          git commit -m "Build üçª"

          git reset production
          git add -f build
          git commit -m "Build üçª"

      - name: Deploy
        if: ${{ success() }}
        run: |
          git push production

      - name: Clear
        if: ${{ always() }}
        run: |
          git switch master
          git branch -D temp/production
